# Generated by Django 4.0.5 on 2022-11-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wordpress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('api_password', models.CharField(default='', max_length=100)),
                ('page', models.IntegerField(default=1)),
                ('tag_page', models.IntegerField(default=1)),
                ('category_page', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('que', models.IntegerField(default=0)),
                ('sync_status', models.CharField(default='nosync', max_length=10)),
            ],
        ),
    ]
