# Generated by Django 4.0.5 on 2022-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('url', models.CharField(default='', max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('page', models.IntegerField(default=1)),
            ],
        ),
    ]
