# Generated by Django 4.0.5 on 2022-11-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='que',
            field=models.IntegerField(default=0),
        ),
    ]
