# Generated by Django 4.0.5 on 2022-11-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='wordpress_status_post',
            field=models.TextField(blank=True),
        ),
    ]
