# Generated by Django 4.0.5 on 2022-11-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordpressCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(default='no category_name name')),
                ('website_name', models.TextField(default='no website')),
                ('detail', models.TextField(default='no detail')),
                ('category_wordpress_id', models.CharField(default='noid', max_length=140)),
                ('wordpress_website', models.TextField(default='nowebsite')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
