# Generated by Django 4.0.5 on 2022-11-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordPressTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.TextField(default='no website')),
                ('tag_name', models.CharField(max_length=100)),
                ('wordpress_website', models.TextField(default='nowebsite')),
                ('wordpress_tag_id', models.CharField(default='noid', max_length=100)),
                ('sync_status', models.CharField(default='nosync', max_length=10)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
